In [2]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset('./data_jobs/')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [4]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [8]:
df['job_country'].isin(['Indonesia']).any()

np.True_

In [9]:
id_jobs = df[df['job_country'] == 'Indonesia']

In [11]:
id_jobs = id_jobs[id_jobs['salary_year_avg'].notna()]
id_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
132684,Data Scientist,Data Scientist - Risk Platform,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-05-02 08:19:40,False,False,Indonesia,year,69962.5,NaN,Cermati.com,"['r', 'python', 'sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
147015,Business Analyst,Junior Business Intelligence Analyst,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-06-10 08:29:05,False,False,Indonesia,year,50400.0,NaN,Cermati.com,"['sql', 'python', 'r', 'bigquery', 'jupyter', ...","{'analyst_tools': ['excel'], 'cloud': ['bigque..."
229531,Data Analyst,Customer Loyalty SLA Control Tower & Data Analyst,"Jakarta, Indonesia",via Ai-Jobs.net,Contractor,False,Indonesia,2023-08-14 07:17:07,False,False,Indonesia,year,105000.0,NaN,Ninja Van,['excel'],{'analyst_tools': ['excel']}
239163,Data Analyst,(Operation) Data Analyst Manual Activity,"Yogyakarta, Yogyakarta City, Special Region of...",via Ai-Jobs.net,Full-time,False,Indonesia,2023-04-05 07:18:38,True,False,Indonesia,year,102500.0,NaN,Ninja Van,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
294963,Machine Learning Engineer,Machine Learning Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-07-24 17:21:49,False,False,Indonesia,year,166000.0,NaN,tiket.com,['tensorflow'],{'libraries': ['tensorflow']}
303696,Data Analyst,Data Analyst (Junior/Entry-level) - Campaign M...,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-24 17:33:21,False,False,Indonesia,year,57500.0,NaN,GoTo Group,['r'],{'programming': ['r']}
305268,Data Engineer,Lead Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-03-02 17:25:23,False,False,Indonesia,year,131580.0,NaN,Cermati.com,"['java', 'python', 'nosql', 'redis', 'redshift...","{'cloud': ['redshift', 'bigquery'], 'databases..."
335117,Senior Data Scientist,Senior Data Scientist - Fraud Modelling,"Central Jakarta, Central Jakarta City, Jakarta...",via Ai-Jobs.net,Full-time,False,Indonesia,2023-01-05 23:40:13,False,False,Indonesia,year,157500.0,NaN,Cermati.com,"['python', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
341109,Data Scientist,Data Science Executive,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-04-10 23:15:41,False,False,Indonesia,year,50400.0,NaN,NielsenIQ,"['python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
343560,Data Analyst,Data Analyst,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-26 23:15:14,True,False,Indonesia,year,57500.0,NaN,Gravel,"['python', 'bigquery']","{'cloud': ['bigquery'], 'programming': ['pytho..."
355207,Business Analyst,Business Intelligence Analyst,"South Jakarta, South Jakarta City, Jakarta, In...",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-08 00:15:43,False,False,Indonesia,year,64800.0,NaN,Moladin,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
377901,Senior Data Engineer,Senior Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-06-06 18:18:55,False,False,Indonesia,year,147500.0,NaN,Carousell Group,"['mongodb', 'mongodb', 'python', 'php', 'go', ...","{'cloud': ['aws', 'redshift'], 'databases': ['..."
404125,Data Analyst,Data Analyst,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-06-08 18:37:59,False,False,Indonesia,year,100500.0,NaN,Stockbit,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
404496,Senior Data Analyst,Senior Analyst FP&A - Data Specialist,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-09-01 18:34:45,True,False,Indonesia,year,109500.0,NaN,GoTo Group,"['sql', 'bigquery']","{'cloud': ['bigquery'], 'programming': ['sql']}"
426363,Data Engineer,DataOps Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-15 16:34:48,True,False,Indonesia,year,72000.0,NaN,GoTo Group,"['sql', 'redis', 'bigquery', 'gcp', 'kubernete...","{'cloud': ['bigquery', 'gcp'], 'databases': ['..."
434286,Data Engineer,Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-03-17 16:32:22,False,False,Indonesia,year,147500.0,NaN,Beautyhaul,"['sql', 'python', 'java', 'c++', 'scala', 'aws...","{'cloud': ['aws', 'redshift'], 'programming': ..."
471660,Data Analyst,Data Analytics Associate,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-09-21 14:27:16,True,False,Indonesia,year,50400.0,NaN,Gravel,"['python', 'bigquery']","{'cloud': ['bigquery'], 'programming': ['pytho..."
514316,Data Analyst,Data Analyst - Junior,Indonesia,via Ai-Jobs.net,Full-time,False,Indonesia,2023-12-15 11:38:21,False,False,Indonesia,year,77017.5,NaN,Samsung Electronics,"['sql', 'python', 'aws', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['aws'],..."
520816,Data Scientist,Data Scientist - GoPay,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-01-30 11:19:18,False,False,Indonesia,year,157500.0,NaN,Gojek,"['python', 'go']","{'programming': ['python', 'go']}"
527097,Software Engineer,BI Developer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-12-19 11:39:07,False,False,Indonesia,year,123000.0,NaN,NTT DATA,"['java', 'python', 'sql', 'no-sql', 'mongodb',...","{'analyst_tools': ['ssis', 'ssrs', 'tableau'],..."
530811,Data Engineer,Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-29 19:37:44,False,False,Indonesia,year,97444.0,NaN,Gravel,"['mysql', 'bigquery', 'spark']","{'cloud': ['bigquery'], 'databases': ['mysql']..."
542880,Senior Data Analyst,Senior Data Analyst - Fraud,"South Jakarta, South Jakarta City, Jakarta, In...",via Ai-Jobs.net,Full-time,False,Indonesia,2023-07-05 19:19:23,False,False,Indonesia,year,111175.0,NaN,Moladin,"['sql', 'sas', 'sas', 'r', 'python']","{'analyst_tools': ['sas'], 'programming': ['sq..."
554451,Senior Data Analyst,Senior Data Analyst - User Trust,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-02-03 19:39:23,False,False,Indonesia,year,111175.0,NaN,BukuWarung,"['sql', 'python', 'r']","{'programming': ['sql', 'python', 'r']}"
574971,Data Scientist,Data Scientist,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-11-04 09:54:41,False,False,Indonesia,year,90000.5,NaN,NielsenIQ,"['tableau', 'atlassian', 'git', 'bitbucket']","{'analyst_tools': ['tableau'], 'other': ['atla..."
586699,Data Engineer,Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-09-04 09:11:27,False,False,Indonesia,year,134241.0,NaN,GoTo Group,"['sql', 'python', 'scala', 'java', 'go', 'reds...","{'cloud': ['redshift', 'gcp', 'bigquery'], 'li..."
586753,Data Analyst,Audit Data Analytics & System Development,"South Jakarta, South Jakarta City, Jakarta, In...",via Ai-Jobs.net,Full-time,False,Indonesia,2023-05-10 09:25:09,False,False,Indonesia,year,64800.0,NaN,Amartha,"['sql', 'sql server', 'excel', 'word', 'powerp...","{'analyst_tools': ['excel', 'word', 'powerpoin..."
603330,Data Analyst,Data Analyst - Ads and Promo Platform,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-06-30 09:19:55,False,False,Indonesia,year,57500.0,NaN,GoTo Group,"['python', 'sql', 'bigquery', 'gitlab', 'asana...","{'async': ['asana'], 'cloud': ['bigquery'], 'o..."
634960,Data Analyst,Data Analyst - Merchant Success,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-02-03 12:39:23,False,False,Indonesia,year,111175.0,NaN,BukuWarung,"['sql', 'python', 'r']","{'programming': ['sql', 'python', 'r']}"
672740,Data Engineer,Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-05-26 10:19:29,False,False,Indonesia,year,147500.0,NaN,Beautyhaul,"['sql', 'python', 'java', 'c++', 'scala', 'aws...","{'cloud': ['aws', 'redshift'], 'programming': ..."
683375,Data Analyst,Marketing Data Analytics Manager,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-03 10:18:35,False,False,Indonesia,year,132500.0,NaN,GoTo Group,"['sql', 'python', 'javascript', 'excel', 'tabl...","{'analyst_tools': ['excel', 'tableau', 'power ..."
713017,Data Analyst,Data Analyst - Consumer Lending,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-30 02:37:44,False,False,Indonesia,year,105000.0,NaN,GoTo Group,"['sql', 'python', 'tableau', 'looker']","{'analyst_tools': ['tableau', 'looker'], 'prog..."
715344,Business Analyst,Associate Business Intelligence,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-10-25 02:17:12,False,False,Indonesia,year,64800.0,NaN,tiket.com,"['sql', 'python', 'shell', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
736512,Data Analyst,Data Analyst,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-12-22 21:17:32,False,False,Indonesia,year,75067.5,NaN,Trusting Social,"['sql', 'r', 'python', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
745091,Machine Learning Engineer,Machine Learning / AI Engineer (Indonesia),"Bandung, Bandung City, West Java, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-06-07 20:55:04,False,False,Indonesia,year,64800.0,NaN,Xtremax,None,None
751658,Data Scientist,Data Scientist (Lending),"South Jakarta, South Jakarta City, Jakarta, In...",via Ai-Jobs.net,Full-time,False,Indonesia,2023-06-22 20:24:06,False,False,Indonesia,year,90670.0,NaN,Moladin,"['sql', 'python']","{'programming': ['sql', 'python']}"
753732,Senior Data Scientist,"Senior Manager, Data Science","Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-01-26 20:21:20,False,False,Indonesia,year,79200.0,NaN,Visa,None,None
766418,Senior Data Engineer,Senior Data Engineer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-08-15 01:17:07,True,False,Indonesia,year,147500.0,NaN,Ninja Van,"['sql', 'python', 'nosql', 'mongodb', 'mongodb...","{'cloud': ['oracle'], 'databases': ['mongodb',..."

In [12]:
id_jobs.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                             37        37.000000              0.0
mean   2023-07-01 11:12:42.135135232     99529.945946              NaN
min              2023-01-05 23:40:13     50400.000000              NaN
25%              2023-05-02 08:19:40     64800.000000              NaN
50%              2023-07-05 19:19:23    100500.000000              NaN
75%              2023-08-29 19:37:44    131580.000000              NaN
max              2023-12-22 21:17:32    166000.000000              NaN
std                              NaN     35543.161352              NaN

In [20]:
id_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median', 'max']).sort_values(by='median')

                             median       max
job_title_short
Business Analyst            64800.0   64800.0
Data Analyst                77017.5  132500.0
Data Scientist              90000.5  157500.0
Senior Data Analyst        111175.0  111175.0
Machine Learning Engineer  115400.0  166000.0
Senior Data Scientist      118350.0  157500.0
Software Engineer          123000.0  123000.0
Data Engineer              132910.5  147500.0
Senior Data Engineer       147500.0  147500.0